//
//  HomePresenter.swift
//  Justo App
//
//  Created by Carlos Villamizar on 6/8/21.
//

import Foundation

protocol HomePresentationLogic {
    func presentProfile(response: Home.Profile.Response)
    func presentError(response: Home.Error.Response)
}

class HomePresenter: HomePresentationLogic {
    
    weak var viewController: HomeDisplayLogic?
    /* Is the class which is responsible for presenting the object which
    is generated by the Interactor.*/
    
    // MARK: - Present SignUp
    func presentProfile(response: Home.Profile.Response) {
        let viewModel = Home.Profile.ViewModel(info: response.info, results: response.results[0])
        viewController?.displayHome(viewModel: viewModel, on: .main)
    }
    
    // MARK: - Present Error
    func presentError(response: Home.Error.Response) {
        let viewModel = Home.Error.ViewModel(error: response.error)
        viewController?.displayError(viewModel: viewModel, on: .main)
    }
}
