# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Justo App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Justo App

pod 'MaterialComponents/TextControls+OutlinedTextAreas'
pod 'MaterialComponents/TextControls+OutlinedTextFields'
pod 'MaterialComponents/TextControls+FilledTextAreas'
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'NotificationBannerSwift', '~> 3.0.0'
pod 'Alamofire', '~> 5.2'
pod 'Kingfisher', '~> 6.0'

  target 'Justo AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Justo AppUITests' do
    # Pods for testing
  end

end
